### ISSUE TITLE
Your website could benefit from having your email address on it

### ISSUE THREAD

**Issue by mikehearn** [TomasMikula/tomasmikula.github.io#1]
I wanted to send you an email and in the end, had to dig out the address from the openjfx-dev archives ... only possible after I remembered I'd seen you post there!

Great though Twitter and GitHub are, they are no substitute for good old fashioned email.

**Comment by TomasMikula** [comment]
And you did manage to find it! 😉 

I used to have my email address public on my GitHub profile, but I was getting emails asking for help with my open-source projects, which I had little motivation to respond to, since that communication should take place in public channels, so that others can respond and others can benefit from the answers. I think hiding my email address was the most effective way to route that traffic to the correct channels.

I figured people with something more personal will find a way to contact me, anyway.

In the future I might reconsider my decision, but keeping it as is for now.
